############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2

# [[main]]
# name = "Elements"
# url = "/elements"
# weight = 3

[[main]]
weight = 4
name = "Blogs"
url = "#"

[[main]]
parent = "Blogs"
name = "Books"
url = "/blog/books"
weight = 1

[[main]]
parent = "Blogs"
name = "Nerdy Stuff"
url = "/blog/nerdy-stuff"
weight = 2

[[main]]
parent = "Blogs"
name = "Blog Series"
url = "/blog/series"
weight = 3

[[main]]
parent = "Blog Series"
name = "Resume Building"
url = "/blog/series/resume-building"
weight = 1

[[main]]
parent = "Blog Series"
name = "Co-operation at IT Companies"
url = "/blog/series/cooperation-at-it-companies"
weight = 2

[[main]]
parent = "Blog Series"
name = "Good Techies Bad Careers"
url = "/blog/series/good-techies-bad-careers"
weight = 3

[[main]]
parent = "Blogs"
name = "Opinions"
url = "/blog/opinions"
weight = 4

[[main]]
parent = "Blogs"
name = "Categories"
url = "/categories"
weight = 5

# [[main]]
# parent = "Pages"
# name = "404 Page"
# url = "/404"

# footer menu
# [[footer]]
# name = "About"
# url = "/about"
# weight = 1

# [[footer]]
# name = "Elements"
# url = "/elements"
# weight = 2

# [[footer]]
# name = "Privacy Policy"
# url = "/privacy-policy"
# weight = 3
